swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /anmelden:
    # binds a127 app logic to a route
    x-swagger-router-controller: VisitorController
    post:
      description: Creates a new Visitor and sends out an invitation.
      # used as the method name of the controller
      operationId: anmelden
      parameters:
        - name: name
          in: body
          description: Name of the Visitor
          required: true
          schema:
            $ref: "#/definitions/VisitorRegisterRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VisitorRegisteredResponse"
        "422":
          description: Email already in database
          schema:
            $ref: "#/definitions/ErrorAlreadyExistsResponse"
        "500": 
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  VisitorRegisterRequest:
    required:
      - name
      - vorname
      - email
      - numguests
    properties:
      name:
        type: string
      vorname:
        type: string
      email:
        type: string
      numguests:
        type: integer
  VisitorRegisteredResponse:
    required:
      - message
    properties:
      message:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: 
          - object
          - array
  ErrorAlreadyExistsResponse:
    required:
      - message
    properties:
      message:
        type: string

